### ISSUE TITLE
Sovellus lagaa

### ISSUE THREAD

**Issue by Zoltus** [Zoltus/UkkoPeli#5]
Sovelluks lagittaa jostain syystä. Pelaan one plus 7t puhelimella

**Comment by miikavainio** [comment]
Mikä versio sulla on?

**Comment by Zoltus** [comment]
> Mikä versio sulla on?

1.0 beta

**Comment by Zoltus** [comment]
> > 
> 
> 2.0 on uusin, päivitä se

kiitos se toimii! WAU KUINKA Nopea tuki!
